UPDATE_UP = 1
UPDATE_DOWN = 2
UPDATE_LEFT = 3
UPDATE_RIGHT = 4
UPDATE_A = 5
UPDATE_B = 6
UPDATE_SELECT = 7
UPDATE_START = 8

# An Update represents an individual delta to the game state that is generated by a user and applied
# by a game to its internal state.
class Update():
    def __init__(self, type: int):
        if type < UPDATE_UP or type > UPDATE_START:
            raise ValueError("Invalid update type")
        self.type = type

    def __str__(self) -> str:
        return f"Update(type={self.type})"