UPDATE_UP = 1
UPDATE_DOWN = 2
UPDATE_LEFT = 3
UPDATE_RIGHT = 4

UPDATE_PAUSE = 5
UPDATE_SELECT = 6

# An Update represents an individual delta to the game state that is generated by a user and applied
# by a game to its internal state.
class Update():
    def __init__(self, button: int, player_index: int):
        if not Update.is_button_valid(button):
            raise ValueError("Invalid update type")
        self.button = button
        self.player_index = player_index

    def __str__(self) -> str:
        return f"Update(button={self.button},player={self.player_index})"
    
    @staticmethod
    def is_button_valid(button: int) -> bool:
        return button >= UPDATE_UP and button <= UPDATE_SELECT   